version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"  # Backend
      - "5173:5173"  # Frontend (Vite default port)
    volumes:
      - .:/app       # Mount project directory for live changes
      - /app/node_modules  # Prevent overwriting node_modules
      - /app/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fixes file watching issues in Docker
